apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookvexe-be-j2e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookvexe-be-j2e
  template:
    metadata:
      labels:
        app: bookvexe-be-j2e
    spec:
      containers:
        - name: bookvexe-be-j2e
          image: bookvexe-be-j2e:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secrets
                  key: GOOGLE_CLIENT_SECRET